### ISSUE TITLE
Typing error with `DataHelper.get_element_text`

### ISSUE THREAD

**Issue by cmutel** [sami-m-g/pyecospold#15]
`DataHelper.get_element_text` is supposed to always return a `str`, but calls `get_element`, which can return `None`. Pyright is not happy.

**Comment by sami-m-g** [comment]
@cmutel `DataHelper.get_element_text` is set to return a default value of `Defaults.TYPE_DEFAULTS[str]` in that case.

**Comment by cmutel** [comment]
Don't shoot me, I am just the messenger!
<img width="977" alt="Screenshot 2023-01-15 at 15 43 20" src="https://user-images.githubusercontent.com/645217/212547523-dca397d8-174f-4293-bea5-bd7627bb206d.png">
I don't think this is a real issue, we know a "text" element which follows the XSD will be a `str`, and if falsely will get a replacement with `Defaults.TYPE_DEFAULTS[str]`; I wonder if there is a way to get pyright to realize this. BTW, pyright is from Microsoft so somehow I am holding you a bit responsible :p

**Comment by sami-m-g** [comment]
I found the issue which was that `Defaults.TYPE_DEFAULTS[str]` itself was declared as `Any` since `Defaults.TYPE_DEFAULTS` holds the defaults for different data types hence the return type is `Any`. b6793578a321e75afdbbebbe3dc967e705b65457 resolved this by wrapping `Defaults.TYPE_DEFAULTS[str]` with a `str()`.
